// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Generate your api key',
    appId: 'Get your app Id',
    messagingSenderId:'get your sender ID',
    projectId: 'create your project Id',
    authDomain: '',
    storageBucket: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Generate your api key',
    appId: 'Get your app Id',
    messagingSenderId: 'get your sender ID',
    projectId: 'create your project Id',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:'Generate your api key',
    appId:'Get your app Id',
    messagingSenderId: 'get your sender ID',
    projectId:  'create your project Id',
    storageBucket: 'create your project Id',
    iosClientId: '',
    iosBundleId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Generate your api key',,
    appId:'Get your app Id',
    messagingSenderId: 'get your sender ID',
    projectId: 'create your project Id',
    storageBucket: 'notes-app-489a9.appspot.com',
    iosClientId: '',
    iosBundleId: '',
  );
}
// Basicly delete this file and create yours
