// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzY5j0RDbuzqVAGgQoEbCYetYRmbH-IvM',
    appId: '1:931337952785:web:22e587d9c55c4ba4f15bb0',
    messagingSenderId: '931337952785',
    projectId: 'notes-app-489a9',
    authDomain: 'notes-app-489a9.firebaseapp.com',
    storageBucket: 'notes-app-489a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpV-eLalJ_adu4kXzRgMszxDH1kxPkL_A',
    appId: '1:931337952785:android:ab4829dac6a62fa2f15bb0',
    messagingSenderId: '931337952785',
    projectId: 'notes-app-489a9',
    storageBucket: 'notes-app-489a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxxLEfezc-j8TZFbamNvlqrpQVm92yC7A',
    appId: '1:931337952785:ios:9afab3f34ec95852f15bb0',
    messagingSenderId: '931337952785',
    projectId: 'notes-app-489a9',
    storageBucket: 'notes-app-489a9.appspot.com',
    iosClientId: '931337952785-afurphau4inb1a9ncuc4pt9cg103ils3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxxLEfezc-j8TZFbamNvlqrpQVm92yC7A',
    appId: '1:931337952785:ios:9afab3f34ec95852f15bb0',
    messagingSenderId: '931337952785',
    projectId: 'notes-app-489a9',
    storageBucket: 'notes-app-489a9.appspot.com',
    iosClientId: '931337952785-afurphau4inb1a9ncuc4pt9cg103ils3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
